# Generated by Django 5.1.7 on 2025-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "clean_invalid_json_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="allergies",
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="illnesses",
            field=models.JSONField(blank=True, null=True, default=list),
        ),
    ]
