# Generated by Django 5.1.7 on 2025-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Appointment date. Auto-populated from schedule if not provided.', null=True)),
                ('start_time', models.TimeField(help_text='Appointment start time. Must exactly match one of the schedule’s available slots.')),
                ('end_time', models.TimeField(help_text='Appointment end time. Must exactly match one of the schedule’s available slots.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled')], default='pending', help_text='Current status of the appointment.', max_length=20)),
                ('appointment_type', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], default='physical', help_text='Type of appointment (physical or online). Auto-populated from schedule if not provided.', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation, if applicable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
