# Generated by Django 5.1.7 on 2025-03-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where the appointment takes place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.clinic'),
        ),
    ]
