# Generated by Django 5.1.7 on 2025-03-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(help_text='Duration in minutes for each appointment slot.')),
                ('appointment_type', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], default='physical', help_text='Indicates whether this schedule is for            online or physical appointments.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.clinic')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
