# Generated by Django 5.1.7 on 2025-03-28 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['date', 'is_active'], name='schedules_d_date_050878_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'clinic'], name='schedules_d_doctor__1a4d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['is_active'], name='schedules_d_is_acti_065ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['appointment_type'], name='schedules_d_appoint_b73924_idx'),
        ),
    ]
