# Generated by Django 5.1.7 on 2025-04-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(help_text='Unique National or IQAMA ID of the dependent.', max_length=50, unique=True)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to the guardian (e.g., Child, Spouse).', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, help_text='The User account created for the dependent, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_profile', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(help_text='The KFUPM-affiliated user acting as guardian for this dependent.', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guardian'], name='dependents__guardia_41e091_idx')],
            },
        ),
    ]
