# Generated by Django 5.1.8 on 2025-05-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0003_initial'),
        ('profiles', '0004_alter_json_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_file', models.URLField()),
                ('prescription_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='Status of the prescription', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to='profiles.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to='profiles.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
