# Generated by Django 5.1.7 on 2025-04-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed Delivery Attempt'), ('returned_to_sender', 'Returned to Sender'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('on_hold', 'On Hold')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('delivery_person', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='profiles.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
