# Generated by Django 5.1.7 on 2025-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, default='', help_text='Auto-filled with English name if not provided', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.TextField(blank=True, help_text='Store the SVG markup or image URL for the clinic logo.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
